service_name: "gin-server-example"
env: "development"
redact_keys: ["password", "Authorization"]

log:
  filename: "gin_app.log"
  max_size: 10
  max_backups: 3
  max_age: 1
  compression: "gzip"
  rotation_interval: 24 # in hours
